# Site settings
author: Marcel Rico
title: A Journey in Code
header-img: img/home-bg.png
email: personal.mr4@gmail.com
copyright_name: Marcel Rico
description: > # this means to ignore newlines until "baseurl:"
  From IT Tech to Software Dev
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MarcelRico

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
